import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "../../lib/utils";
import LenisProvider from "../../lib/providers/lenis-provider";

const camberTrialLight = localFont({
  src: "../../public/fonts/CamberTRIAL-Bd.otf",
  variable: "--font-camber",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Capital engineering consultancy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(camberTrialLight.variable, "no-scrollbar")}>
        {/* <LenisProvider> */}
        {children}
        {/* </LenisProvider> */}
      </body>
    </html>
  );
}
